# Generated by Django 4.2.13 on 2024-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
