# Generated by Django 4.2.13 on 2024-06-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sell_date', models.DateField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_image', models.ImageField(blank=True, null=True, upload_to='sell_images')),
                ('sell_place', models.CharField(blank=True, max_length=254, null=True)),
                ('buyer', models.CharField(blank=True, max_length=254, null=True)),
                ('sell_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
