# Generated by Django 4.2.13 on 2024-06-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sell',
            table='sell',
        ),
    ]
