# Generated by Django 4.2.13 on 2024-06-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0002_alter_creditor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('given_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditors.creditor')),
            ],
            options={
                'db_table': 'credit_history',
            },
        ),
    ]
