# Generated by Django 4.2.13 on 2024-06-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0001_initial'),
        ('expenses', '0002_alter_expense_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='pond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ponds.pond'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('individual', 'Individual'), ('corporation', 'Corporation'), ('shop', 'Shop'), ('family', 'Family'), ('pond', 'Pond')], max_length=30),
        ),
    ]
